### ISSUE TITLE
MD common req C.1 :XML schema

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#238]
TG Requirement C.1: metadata/2.0/req/common/xml-schema;
INSPIRE metadata records shall be encoded in XML format valid against one of the following XML Schemas: - [CSW2 AP ISO] XML Schema13, - [ISO 19139] XML Schema as available in the ISO repository14, or - [ISO 19139] XML Schema as available in the OGC schema repository15.

XML encoded with http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd referring to GML version 3.2.0  failed schema validation;

XML document 'TEST_EU_Metadata_Dataset_2019.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': 'Validation failed: 341:60: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/gml":TimePeriod}'. One of '{"http://www.opengis.net/gml/3.2":AbstractTimePrimitive}' is expected.Validation failed: http://www.isotc211.org/2005/gmd/gmd.xsd, 2:35: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.Validation failed: 65:82: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.isotc211.org/2005/gmx":Anchor}'. One of '{"http://www.isotc211.org/2005/gco":CharacterString}' is expected.'.

Expected behavior is pass to this test, because the used scheme is one of the options of TG Requirement C.1

Tested in the staging environment;
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID838ceb8e-e878-4533-9b77-fef13e7f1329.html

test xml;
[TEST_EU_Metadata_Dataset_2019.zip](https://github.com/inspire-eu-validation/community/files/4287399/TEST_EU_Metadata_Dataset_2019.zip)

**Comment by idevisser** [comment]
Thanx, but that was not the issue,

Problem is that a valid  XML not pass  the validation. I expect that the validator support all options mentioned in the TG INSPIRE, not only one.

Best regards Ine

**Comment by iuriemaxim** [comment]
Hi Ine,

This declaration in the header of the metadata file
xmlns:gml="http://www.opengis.net/gml"
points to GML 3.1.1,

![image](https://user-images.githubusercontent.com/20813598/75961944-963a5a00-5ecb-11ea-89e1-0640d232d2a9.png)


 while INSPIRE TGs are indicating that GML 3.2 should be used, i.e.:

xmlns:gml="http://www.opengis.net/gml/3.2"

If this will be replaced, than there will be an error related to temporal extent in any XML validator due to inconsistencies between the gmd and gml schemas and this is the error that is triggered by the validator as well, because the validator seems not to look in the header of the metadata file.

![image](https://user-images.githubusercontent.com/20813598/75960856-8752a800-5ec9-11ea-86b3-28bf65939559.png)

Actually the validator should report for this metadata file that an error exist in the header of the metadata file as the schema for GML should be 3.2, while it was declared 3.1.

Hope that it helps,
Iurie

**Comment by idevisser** [comment]
Hi Iurie,

http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd is referring to GML version 3.2.0, GML 3.2.0 has target namespace http://www.opengis.net/gml, the same as GML version 3.1.1

Changing the gml declaration to 3.2  in the example XML is not correct. This creates a schema error. 

The point is that  the validator only uses the APISO scheme to validate and not the other scheme's mentioned in the TG INSPIRE.

Best regards Ine

**Comment by iuriemaxim** [comment]
Hi Ine,

You are right, 
First of all the GML schema should point to GML 3.2 (3.2.0 or 3.2.1).
So here is the first error as it should not point to GML 3.1.
Then you should find the correct combination for GMX, GML and GMD schemas in order that all to match the same version of the GML (either 3.2.0, either 3.2.1).

![image](https://user-images.githubusercontent.com/20813598/75962744-009fca00-5ecd-11ea-83af-921558142bdf.png)

**Comment by fabiovin** [comment]
To avoid the http/https redirect problems the MD 2.0 validates against a fixed schema (https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd).
This schema uses the GML 3.2.1 version (namespace = http://www.opengis.net/gml/3.2), therefore the metadata that use the GML 3.2.0 version (namespace = http://www.opengis.net/gml) fails.

Regarding the GML version number, there is a mismatch between ISO TC211 and OGC.
ISO TC 211 names it as 3.2.0, the same is used by TG 2.0 (https://www.isotc211.org/2005/gml/).
OGC names it as 3.1.1 (http://www.ogc.org/standards/gml, http://schemas.opengis.net/gml/).
In any case, the two versions are the same apart from the name.

The TG 2.0 allows the use of the old GML 3.2.0 version (TG requirement C.1) even though it is deprecated (version 3.1.1 in http://www.ogc.org/standards/gml).

We are working on the issue in order to allow the validator to validate a metadata 2.0 according to the proper schema in relation to the GML version used.

**Comment by iuriemaxim** [comment]
It would be a major improvement of the validator if it would also analize the header of the files, including if the XSD schemas would be cached locally and also publicly available and synchronized with the original.

**Comment by iuriemaxim** [comment]
Hi @fabiovin,

Thank you for the clear explanation. Most probably nobody could guess that GML OGC version 3.1.1 is actually 3.2.0 and that if the TG is indicating the use of GML 3.2, than OGC GML 3.1.1 can be used.

And can you please provide a reference where it is written that OGC GML 3.1.1 (here are all GML versions http://schemas.opengis.net/gml/) is actually GML 3.2.0. 
At least in the links bellow it can be found any such information, and these are the Release Notes:
http://schemas.opengis.net/gml/3.1.1/gml_3_1_1-ReadMe.txt
http://schemas.opengis.net/gml/ReadMe.txt

ISO is indicating that GML Schema version 3.2.0 is **ISO/DIS 19136** (https://www.isotc211.org/2005/gml/), while the title of the Technical Guideline is pointing to **ISO/TS 19139**: ”Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007”.

To be easier to understand, can you please provide/confirm/complete the links to the XSD schemas for these two scenarios, including for SRV that is used for Network services metadata:

In order to use GML 3.2.1 than URLs of the schemas should be:
GML: http://schemas.opengis.net/gml/3.2.1/gml.xsd or .........................................
GMX: http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd or http://schemas.opengis.net/iso/19139/20070417/gmx/gmx.xsd or .........................................
GMD:  http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd or http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd or http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd or .....................................................
SRV: http://schemas.opengis.net/iso/19139/20070417/srv/1.0/srv.xsd or .........................................

In order to use GML 3.2.0, than URLs of the schemas should be:
GML: http://schemas.opengis.net/gml/3.1.1/base/gml.xsd or https://www.isotc211.org/2005/gml/gml.xsd or .........................................
GMX: http://schemas.opengis.net/iso/19139/20060504/gmx/gmx.xsd. or .........................................
GMD: http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd or .........................................
SRV: http://schemas.opengis.net/iso/19139/20060504/srv/srv.xsd or .........................................

I think that It would be highly appreciated by all data providers.

If the above are correct, than it means that if GML 3.2.0 (3.1.1) will be used, then the header of the Metadata files made according to the Metadata TG version 2.0 would be the same with the header of the metadata files made according to TG version 1.3 even if the titles of the two TGs are different and are indicating different ISO standards.

**Comment by ghost** [comment]
Hi @fabiovin ,

I have consolidated given information and links in the following table:

| # | apiso from | apiso version | Imports/Includes from | GML version - OGC notation | GML version - ISO TC211 notation | schema locations accessible |
| ------ | ------ |  ------ | ------ | ------ | ------ | ------ |
| 1 | [INSPIRE](https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd)  | 1.0.0 | http://schemas.opengis.net/iso/19139/20070417/ | [3.2.1](http://www.opengis.net/gml/3.2) | unknown | YES
| 2 | [OGC](http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd)  | 1.0.1 | http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas http://schemas.opengis.net/iso/19139/20070417/ | [3.1.1](http://schemas.opengis.net/gml/) | [3.2.0](https://www.isotc211.org/2005/gml/) -> [deprecated](http://www.ogc.org/standards/gml) | [NO](http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas) |

**GML 3.2.1** support: 

1. TG 2.0 - NO
2. INSPIRE Validator - YES (staging/production instance)

**GML 3.2.0** support:

1. TG 2.0 - YES but deprecated
2. INSPIRE Validator - NO

Is this table and information regarding support in Validator and TGs correct? Feel free to add or change information in the table.

Thanks in advance.

**Comment by danielnavarrogeo** [comment]
Dear @idevisser 

Thank you for raising this issue. The validator is not currently taking into account the schema http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd referring to GML version 3.2.0.

We will fix it and let you know when it is ready.

Regards

**Comment by fabiovin** [comment]
Dear @DeordD,
please take into consideration that the apiso schema, you mentioned at point 2 of your table, refers to GML 3.2.0 version (or 3.1.1 for OGC) and not to the 3.2.1 one.
In addition, TG 2.0 supports the use of the GML 3.2.1 version.

I will try to clarify the state of the schemas with a table.

**Comment by ghost** [comment]
Dear @fabiovin ,

thanks a lot for the feedback.

Kind regards.

**Comment by danielnavarrogeo** [comment]
Dear @idevisser 

The issue has been addressed and it can be tested in [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Additionally, thank you @fabiovin, @DeordD and @iuriemaxim  for clarifying the different schemas available.

Regards

**Comment by idevisser** [comment]
Dear @danielnavarrogeo 

There are no problems anymore with the schema validation, so this is a good improofment, but there is still an issue with temporal extent. I think it is related because this metadata element is a gml element;

Error message; XML document 'TEST2_EU_Metadata_Dataset_2019.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': The metadata record has a temporal extent, but timePosition or timePeriod must be provided.

I used this test XML
[EU_TEST2_.zip](https://github.com/inspire-eu-validation/community/files/4312752/EU_TEST2_.zip)

expected behavior, no fails, because the timePeriod is provided.

Best regards Ine

**Comment by danielnavarrogeo** [comment]
Dear @idevisser 

The issue with TimePeriod element has been addressed.

Could you please check it and provide us feedback?

Regards

**Comment by idevisser** [comment]
Dear @danielnavarrogeo 

Thnx, it works as expected!

Best regards Ine

**Comment by danielnavarrogeo** [comment]
Thank you @idevisser for your feedback.

Regards

**Comment by fabiovin** [comment]
Dear all,
even though the related requirement (TG Requirement C.1) mentions only the gmd schema (see the second schema in the third bullet point in the related ATS https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md) the other two schemas (gmx for anchor elements and srv for service metadata elements) are, in any case, needed for a proper validation of dataset and service metadata.
For this reason, we created a wrapper xsd (https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/iso_19139_20060504/iso_19139_20060504_wrapper.xsd) which includes all necessary schemas:

- GMX: http://schemas.opengis.net/iso/19139/20060504/gmx/gmx.xsd
- GMD: http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd
- SRV: http://schemas.opengis.net/iso/19139/20060504/srv/srv.xsd

Now the validator uses this wrapper schema for validation of metadata that refer to 2006 schemas.

This further change was included in the latest version of the INSPIRE Reference Validator, released on April 15.
