### ISSUE TITLE
Problems starting etf-webb - changes in teamengine ?

### ISSUE THREAD

**Issue by MetaGIS** [INSPIRE-MIF/helpdesk-validator#461]
We have the validator deployed as a national instance but have since a day not been able to start etf-webapp
Same instance worked fine up to last week.

It is version 2020.3 deployed in Tomcat on a linux-server
http://etf.geodatavalidering.se/etf-webb

We now have tried to reinstall it but still have problems.

We now think it seems depend on updates on 
http://cite.opengeospatial.org/teamengine/rest/suites

The error we get is
Caused by: java.lang.IllegalArgumentException: A version in the format MAJOR.MINOR or MAJOR.MINOR.PATCH is required: "wfs20"
	at de.interactive_instruments.Version.set(Version.java:102)
	at de.interactive_instruments.Version.<init>(Version.java:78)
	at de.interactive_instruments.Version.parse(Version.java:90)

It seems to be changes in how wfs20 is defined. It looks like a dotted version is required
Maybe it should be defined as wfs2.0
http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/

Kind Regards
Michael Östling

**Comment by carlospzurita** [comment]
We were aware of this issue last Friday. As you correctly pointed out, this is due to a dependency on the TEAM engine, and the way the version was set up. We published a hotfix on the production instance, and have modified both the Docker image and the inspire-validator zip file on the release.

We are looking into the best way to notify all users of this change and make them aware that they need to download the modified validator.

**Comment by MetaGIS** [comment]
Thanks for quick reply
Its easy to upgrade the validator if we get a new revision
But on the webpage I see no updated release.
https://github.com/inspire-eu-validation/community/releases

/Michael

**Comment by botenvouwer** [comment]
At PDOK in the Netherlands we also get this issue. The hotfix is not fixing it for us. We'll still get the 503 http response.

**Comment by carlospzurita** [comment]
We have created a [new release](https://github.com/inspire-eu-validation/community/releases/tag/v2020.3.1), and uploaded a new version of the Docker image docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.3.1 . Please clean your docker images and use this new one.

**Comment by MetaGIS** [comment]
The fix solved the validation where we run the WAR directly in tomcat on Linux machine
Thanks!

/Michael Östling

**Comment by marcingrudzien** [comment]
I have downloaded and deployed a new docker image 2020.3.1 and I still see the error in docker logs "CreationException: Error creating bean with name 'testDriverController': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: A version in the format MAJOR.MINOR or MAJOR.MINOR.PATCH is required: "wfs20""

Validator endpoint  returns "HTTP ERROR: 503 Problem accessing /validator/. Reason: Service Unavailable"

Marcin Grudzień

**Comment by carlospzurita** [comment]
Dear @marty1357 

Did you cleaned the Docker images on your side? You may have some cache issues. Other users have downloaded the new Docker image and have been able to deploy it without issues.

**Comment by marcingrudzien** [comment]
Dear @carlospzurita

Once more I have deleted all containers and images, cleared docker cache and restarted the server. Next, I have downloaded and deployed a new image following steps form https://github.com/inspire-eu-validation/community/releases/tag/v2020.3.1 and still I get the same error. I attach a log file 
[docker.zip](https://github.com/inspire-eu-validation/community/files/5630179/docker.zip)


Best regards,
Marcin

**Comment by carlospzurita** [comment]
Dear @marty1357 

Are you also clearing the `~/etf` folder used as volume? That also is part of the Docker container, and can contain old references of the Docker image.

**Comment by marcingrudzien** [comment]
Dear @carlospzurita 

Cleaning ~/etf partially helped. The application starts now. However, when I want to launch the application in a browser all I can see is a **blank, white page**. In the container log, I find many warnings like the one below. They update every time I reload the application in the browser

2020-12-02 15:47:40.816:WARN:oejh.HttpParser:qtp1973538135-16: Illegal character 0x16 in state=START for buffer HeapByteBuffer@7e974c70[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03\r\xB5\x9d\x83M\x8d-...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>ent=%7B%22a%22%3A...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}

Best regards,
Marcin

**Comment by marcingrudzien** [comment]
I also noticed that application when launched tries to download https://192.168.103.30:8080/validator/js/lib/require.min.js library. However, the file cannot be loaded because HTTPS is not supported by the local server on the local URL. See a screenshot
![Przechwytywanie](https://user-images.githubusercontent.com/25637709/100900085-c3e81a00-34c2-11eb-8176-883ee99d14fe.PNG)
As a result, the application does not start properly.

**Comment by reinij** [comment]
Dear @marty1357 

I had similar issues, but I then built myself and now it works

1) wget https://github.com/inspire-eu-validation/community/releases/download/v2020.3.1/inspire-validator-2020.3.1.zip
2) jar xfv inspire-validator-2020.3.1.zip
3) docker build -t inspire-validator-2020.3.1 .
4) docker run -p 8080:8080  inspire-validator-2020.3.1 (I used 80:8080 but otherwise similar)

I hope this helps.

**Comment by marcingrudzien** [comment]
Dear Jari,

Your way worked. Thank you.
Additionally, I had to allow execute permission to the file docker-entrypoint.sh

Best regards,
Marcin

**Comment by carlospzurita** [comment]
We are closing this issue as it seems all problems were gone. 
If the problem persists, please, feel free to open a new issue.
