### ISSUE TITLE
Unexpected Temporal Filter validation issues in Direct WFS test

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#541]
When validating this [PLU WFS](https://geodienste.komm.one/ows/services/org.506.78427a5b-2f82-4311-ba7d-74eb7b8c10f4_wfs/org.506.e21f771b-0d06-4dbc-b246-60aa8d12ed52?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) using the Direct WFS test, it fails several tests in the "Temporal Filter" category: https://inspire.ec.europa.eu/validator/v2/TestRuns/EID30da35f3-a06f-4050-90de-feac32d57afe.html
There are two kinds of errors occuring:

1. for example the test with the test Id "EID88ffdb3b-eb8e-30e4-b975-e4881bb0a7f8"
![grafik](https://user-images.githubusercontent.com/34163838/115402681-eb2e5200-a1eb-11eb-8a25-076cbc4bae5e.png)

The error message is "No temporal values found in results: property is "http://inspire.ec.europa.eu/schemas/plu/4.0":validFrom. expected [false] but found [true]". 

This is the saved response from the validator: 
[EID9e24fede-9a4c-4a29-9880-0932b1df6ad8.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6344099/EID9e24fede-9a4c-4a29-9880-0932b1df6ad8.zip)

2. for example the test with the test Id "EIDe6665990-05d7-3e77-a3a8-0893f896fdca" 
![grafik](https://user-images.githubusercontent.com/34163838/115403717-f9c93900-a1ec-11eb-8116-442bde8b16bb.png)

The error message is "t1 (Period: 2012-04-04T00:00:00.000-0400/2012-04-04T23:59:59.999-0400) is not related to t2 (Period: 2012-04-04T16:19:59.999-0400/2012-04-05T00:59:59.998-0400): BEFORE. The actual temporal relation is OVERLAPS."

This is the saved response from the validator: 
[EIDa5cc6da8-bfcb-4adc-992f-989777e0f525.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6344105/EIDa5cc6da8-bfcb-4adc-992f-989777e0f525.txt)

In both cases, it looks like the validator is trying to test something using values of the data contained in the WFS, but with the error message provided, I would not know how this leads to the WFS not being valid.

The gml file deliverd via the WFS passes the PLU conformance tests.

Could you please help interpreting the error messages in case it really is an error or make sure that the tests do not detect errors here?

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

This error is coming from the OGC TEAM engine validator, which is used as a dependency on the Direct WFS ETS. We only process the result of the validation through the endpoint in their service and include it in the Test Report. You can open the issue non their Github repository https://github.com/opengeospatial/teamengine , and include the result of the validation in using the their own TestReport format through the request https://cite.opengeospatial.org/teamengine/rest/suites/wfs20/run?wfs=https://geodienste.komm.one/ows/services/org.506.78427a5b-2f82-4311-ba7d-74eb7b8c10f4_wfs/org.506.e21f771b-0d06-4dbc-b246-60aa8d12ed52?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

**Comment by JohannaOtt** [comment]
@carlospzurita Thank you for the feedback. The proposed request https://cite.opengeospatial.org/teamengine/rest/suites/wfs20/run?wfs=https://geodienste.komm.one/ows/services/org.506.78427a5b-2f82-4311-ba7d-74eb7b8c10f4_wfs/org.506.e21f771b-0d06-4dbc-b246-60aa8d12ed52?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0 is running into a Status Code 500 unfortunately.

I therefore ran the test via the Team Engine interface. FYI: It is reporting NullPointerExceptions for the tests I described above 
![grafik](https://user-images.githubusercontent.com/34163838/115518243-3bf38880-a288-11eb-9cd3-a32278ddd516.png)
So you might also want to check why NullPointerExceptions in the Team Engine lead to the error messages reported above that are displayed in the INSPIRE Validator.

I created [this issue](https://github.com/opengeospatial/teamengine/issues/470) in the Team Engine GitHub repository now.

**Comment by JohannaOtt** [comment]
> So you might also want to check why NullPointerExceptions in the Team Engine lead to the error messages reported above that are displayed in the INSPIRE Validator.

Explanation for the difference: The OCG Validator beta version returns the same results as the INSPIRE Validator

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

it seems the related issue in the OGC repository has been solved, do you confirm that the error is no more present?

**Comment by JohannaOtt** [comment]
The error mentioned under no. 2 is still occurring and is covered in this OGC Team Engine issue:
- https://github.com/opengeospatial/ets-wfs20/issues/185

So I would tend to keep this one open as other INSPIRE validator users might run in the same issue and can find the link to the relevant OGC Team Engine issue with it.
But in the end, it is up to you to decide if you want to "mirror" the OGC Team Engine tickets in such cases or not.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

it seems that also the second OGC issue was closed, so I will close this issue.
Please reopen it if the error persists.

**Comment by JohannaOtt** [comment]
@fabiovinci When validating the WFS from the issue description against the staging instance (production instance currently not functional), the error described under no. 2 is still occurring. So seems like the fixed from the OGC validator are not yet represented in the INSPIRE validator. 
Unfortunately, I cannot re-open this issue myself.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,
we will test the service in production and compare results.

**Comment by fabiovinci** [comment]
The fix for the OGC issue https://github.com/opengeospatial/ets-wfs20/issues/185 is assigned to milestone 1.39, but the one included in the [Official OGC Validator](https://cite.opengeospatial.org/teamengine/) is 1.38, so the fix is not currently available in the INSPIRE Validator.

The correct implementation of the fix of your issue could be tested in the [Beta OGC Validator](https://cite.opengeospatial.org/te2/) which implements the 1.40 version of the WFS2.0 specification.

We will leave the issue open until the related fix is available in the Validator.

**Comment by fabiovinci** [comment]
Dear all,
since version 1.40 of the WFS 2.0 specification is now included in the production instance, this error should no longer be present.
We will close the issue. Please reopen it if the error persists.

**Comment by JohannaOtt** [comment]
Hi Fabio,

Thank you for reaching out.
I validated the [WFS from the original issue description](https://geodienste.komm.one/ows/services/org.506.78427a5b-2f82-4311-ba7d-74eb7b8c10f4_wfs/org.506.e21f771b-0d06-4dbc-b246-60aa8d12ed52?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) against the INSPIRE validator (production instance) and all temporal filter tests are passing now.
So I can confirm that this issue can be closed.

Wishing you and the team happy holidays!


All the best
Johanna
