### ISSUE TITLE
Internal error messages when validating Land Cover data

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#704]
When validating a Land Cover dataset, there are two internal errors in the testsuite:
1. Conformance Class: Data consistency, Land Cover is displayed blue in the result and is not executed with "The Test Suite was not executed because the Test Driver returned an error."
2. Conformance Class: Application schema, Land Cover nomenclature, test lc-as.a.1 description is failing with "The Test Suite was not executed because the Test Driver returned an error."

To help us investigate the issue, you may want to include:

- validate the dataset attached against the LandCover test on the production instance 
[he_inspire_lcv_alkis_25832-10_25th.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7976833/he_inspire_lcv_alkis_25832-10_25th.zip)
- Firefox 96.0.3 on Windows 10
- ![grafik](https://user-images.githubusercontent.com/34163838/151933644-ca02de59-884c-4e44-aaac-186548013e82.png)
- ![grafik](https://user-images.githubusercontent.com/34163838/151933718-e4a16937-15c8-430c-bf83-8e661a250292.png)
- [Test run on 08 48 - 01.02.2022 with test suite Annex II - Land Cover (LC).html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7976838/Test.run.on.08.48.-.01.02.2022.with.test.suite.Annex.II.-.Land.Cover.LC.html.zip)
- tests EIDf67a480e-616b-4cd5-b94b-8b729dfaae27 and EID47308633-6a75-4d9b-a159-8e08c3dd74ef

All the best

Johanna

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

Thank you for your message. We are going to analyze the issue, we will come back to you once we have a response.

Best regards

**Comment by arantzaetxebarria** [comment]
Dear @JohannaOtt 

We have developed a solution for your issue and it is in staging environment. Could you please verify that all is working correctly? Thanks in advance.

Regards,

Arantza

**Comment by JohannaOtt** [comment]
@arantzaetxebarria I can confirm that the issue is solved for one of the reported cases (Conformance Class: Application schema, Land Cover nomenclature, EID47308633-6a75-4d9b-a159-8e08c3dd74ef)
But not for the other one (Conformance Class: Data consistency, Land Cover, EIDf67a480e-616b-4cd5-b94b-8b729dfaae27)
![grafik](https://user-images.githubusercontent.com/34163838/156335716-d1a2d0a7-58c1-4b96-a371-0e3ce78b0fc6.png)
[Test run on 10 25 - 02.03.2022 with test suite Annex II - Land Cover (LC).html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8168445/Test.run.on.10.25.-.02.03.2022.with.test.suite.Annex.II.-.Land.Cover.LC.html.zip)

**Comment by arantzaetxebarria** [comment]
Dear @JohannaOtt 

Thank you for your testing and feedback. We will analyze this second issue deeper. As soon as we have a solution we will keep you informed.

Regards

**Comment by arantzaetxebarria** [comment]
Dear @JohannaOtt 

It seems that this other issue (Conformance Class: Data consistency, Land Cover) is solved, see the report in the staging environment http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID02bdd1ff-2633-4fd4-91ff-1ed698ce1a3c. Could you please confirm us? If all is correct, we will add the fix (Conformance Class: Application schema, Land Cover nomenclature) to the release that will take place in the next few days. Thanks

Regards

**Comment by JohannaOtt** [comment]
@arantzaetxebarria LGTM, the conformance class is now executed. Issue can be closed from my perspective.

**Comment by JohannaOtt** [comment]
@arantzaetxebarria Sorry to say but the "Conformance Class: Data consistency, Land Cover" issue is back - both on productive and staging:
![grafik](https://user-images.githubusercontent.com/34163838/160856082-ee63c185-6817-4622-af12-267c36cb21cd.png)
This is the error message:
"de.interactive_instruments.exceptions.StorageException: javax.xml.bind.MarshalException
 with linked exception:
[javax.xml.bind.MarshalException
 with linked exception:
[Exception [EclipseLink-25003] (Eclipse Persistence Services - 2.7.0.v20170811-d680af5): org.eclipse.persistence.exceptions.XMLMarshalException
Exception Description: An error occurred marshalling the object
Internal Exception: org.eclipse.persistence.oxm.record.ValidatingMarshalRecord$MarshalSAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.interactive-instruments.de/etf/2.0":startTimestamp}'. One of '{"http://www.interactive-instruments.de/etf/2.0":resultedFrom}' is expected.]]"

Unfortunately, I do not seem to habe the rights to re-open the issue. Maybe you or @fabiovinci could do so.

**Comment by arantzaetxebarria** [comment]
Dear @JohannaOtt 

I have tested your example in production and now it seems that is working.

![image](https://user-images.githubusercontent.com/64014694/172790513-f8771873-778f-44f5-b0c2-37c5547d275f.png)


[Test run on 09_26 - 09.06.2022 with test suite Annex II - Land Cover (LC).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8867939/Test.run.on.09_26.-.09.06.2022.with.test.suite.Annex.II.-.Land.Cover.LC.zip)

Could you please verify? thanks 
Regards

**Comment by JohannaOtt** [comment]
@arantzaetxebarria For me, it is still occurring on both instances 
![grafik](https://user-images.githubusercontent.com/34163838/173034154-51f2ba75-bc41-49f3-bb61-7336979a6aba.png)

**Comment by fabiovinci** [comment]
Dear all,

it is very strange, I tryed right now and I don't have the reported error: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID34645a06-32f2-4002-a6aa-abd8be54dab6.

@JohannaOtt, do you confirm you are re-testing the same dataset provided in the first comment?

**Comment by JohannaOtt** [comment]
@fabiovinci Yes, I can confirm that.
When I tried again today, the test was executed and the data validated for it. Same browser etc., so I would not have expected that.
I would propose to close this issue for now and if I run into the issue again, I will open it again.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

thank you for your feedback.
We will close this issue, please open a new one if the problem persists, since with this issue we fixed one of the two errors you reported and the solution was included in the previous release.
Thank you.
