### ISSUE TITLE
Could not create envelope for feature type: {http://inspire.ec.europa.eu/schemas/sd/4.0}SpeciesDistributionDataSet

### ISSUE THREAD

**Issue by Claudia-WE** [INSPIRE-MIF/helpdesk-validator#877]
When validating the following WFS `https://haleconnect.com/ows/services/org.923.c06ef455-1a6b-4259-a31d-b59bb8c7bf09_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0` in INSPIRE Validator both production and staging version I get the following error message:

`Spatial Filter` e.g. `intersectsCurve` but also in other sections:
`Die OGC TEAM Engine hat folgenden Fehler gemeldet: Could not create envelope for feature type: {http://inspire.ec.europa.eu/schemas/sd/4.0}SpeciesDistributionDataSet`

And in  `getCapabilities` `Expect no exception`
`The server experienced a several unexpected error. Please, try again later. if the problem persist, please contact with the helpdesk.`

Can you please help me on that ? Is this a problem of the validator or is there a problem with the WFS ?

Best regards
Claudia

The dataset seems fine to me

**Comment by fabiovinci** [comment]
Dear @Claudia-WE,

the first type of error is related to the OGC Test suite and looking at the related repository it seems it is already fixed and will be implemented soon (https://github.com/opengeospatial/ets-wfs20/issues/247#issuecomment-1320234244).

Regarding the second type of error, it seems the validator tries to access your service by adding the port number (_:443_) in the URL and this generates an exception. We will check if the problem is on the validator side or on your service.

![image](https://user-images.githubusercontent.com/22212406/203301389-8cfc9b1f-10d6-4bb3-872b-226b08795953.png)

**Comment by arantzaetxebarria** [comment]
Dear @Claudia-WE 

I have just tested your service WFS and now the second error (getCapabilities --> Expect no exception) is working properly.
Report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDcc6e52e4-7698-41d7-b2a0-c302728b54c5
![image](https://user-images.githubusercontent.com/64014694/207567918-183686dc-1e0d-4c13-ae4d-cffb6f5c1122.png)

Could you please verify? Thanks

**Comment by Claudia-WE** [comment]
Dear Validator-Team,

Both reported errors still appear.
https://haleconnect.com/ows/services/org.923.c06ef455-1a6b-4259-a31d-b59bb8c7bf09_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0
Could you please recheck and comment ?
Best regards
Claudia Schulte

**Comment by Claudia-WE** [comment]
Dear Validator-Team,

you wrote:
> Regarding the second type of error, it seems the validator tries to access your service by adding the port number (:443) in the URL and this generates an exception. We will check if the problem is on the validator side or on your service.
What was the outcome here ?

Best regards
Claudia

**Comment by Claudia-WE** [comment]
Dear Validator-Team,

you wrote:

> Regarding the second type of error, it seems the validator tries to access your service by adding the port number (:443) in the URL and this generates an exception. We will check if the problem is on the validator side or on your service.

What was the outcome here ?
Our point of view is that the port 443 is correct.

Best regards
Claudia

**Comment by fabiovinci** [comment]
Dear @Claudia-WE,

your server is affected by the same schema error I reported [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/774#issuecomment-1432962497).

Could you please verify and fix it before checking for other errors?

**Comment by fabiovinci** [comment]
Dear @Claudia-WE,

it seems the error related to port 443 has been identified and solved, please have a look at the latest comments on issue #774.

So, you should remove the explicit port declaration in the URLs in the GetCapabilities document.

**Comment by fabiovinci** [comment]
Dear @Claudia-WE,

> So, you should remove the explicit port declaration in the URLs in the GetCapabilities document.

It seems this was fixed on the server side, so the related errors are no longer present.
